### ISSUE TITLE
Getting new path of saved image

### ISSUE THREAD

**Issue by joeywittig** [natsuk4ze/gal#124]
Hi all,

I couldn't find it, but how do i get the new path of the image? I am using the ImagePicker library to take the picture, however this library creates a file in the cache of the app directory. After i move it to the gallery i would like to delete the cached file and continue with the new path. How would one proceed with this?

Thanks!

**Comment by natsuk4ze** [comment]
Hi @joeywittig thank you for contribution 🤝
> this library creates a file in the cache of the app directory.

Is this about Android? Then that **cache** could be the file itself, not the cache. android 10 and later generally saves media in the apps folder and reflects it in the gallery by the MediaStore library.

Also, currently `gal` does not provide a way to retrieve the path after saving. Please consider creating a new issue as a Feature Reuquest if needed.

If you have any questions, feel free to mentions me!

**Comment by natsuk4ze** [comment]
hmmm. this transition may has a problem.

**Comment by joeywittig** [comment]
my bad, ImagePicker makes a cached version of the file.

**Comment by natsuk4ze** [comment]
Hi @joeywittig Thank you for your contribution 🤝

Yes. latest version of this package should not include the operation of saving to the app directory.

**Comment by natsuk4ze** [comment]
Note that there is currently no functionality in this package to retrieve the path after saving. If you need it, please consider registering a feature request issue.

If you have any questions, feel free to mention me! If not, I would be happy to close this🙂
