### ISSUE TITLE
Unsupported file formats Error for existed files

### ISSUE THREAD

**Issue by husen-hn** [natsuk4ze/gal#162]
### Did you check the documentation and it did not help?

- [X] I have searched the [existing documentation](https://github.com/natsuk4ze/gal/wiki)
- [X] I have searched the [existing answer](https://github.com/natsuk4ze/gal/discussions)
- [X] I have read the [contribution guide](https://github.com/natsuk4ze/gal/blob/main/CONTRIBUTING.md)

### Overview

after converting the files using FFmpeg ... the generated files can be accessed and run without any problems through the file manager. but when I use `Gal` to display it inside the gallery, I get an `Unsupported file formats` error.

### Steps to reproduce

1. add FFmpeg package  `ffmpeg_kit_flutter_full_gpl: '6.0.3-LTS`
2. add `filesystem_picker: ^3.1.0` to pick file from system
3. `gal: ^2.1.2`
4. convert a picked video to formats like mp4, avi, mkv, and ...
5. after the converting process done
6. check the converted video from File Manager for sure if it is done successfully
7. save the converted video to the gallery using `Gal`
8. geting error `Unsupported file formats` 

### Code sample

<details><summary>Code sample</summary>

```dart
String selectedFilePath =
        '/data/user/0/com.test.fmkr/cache/file_picker/VID_20230428_140439.mp4';
    String outputPath =
        ' /storage/emulated/0/Movies/fmkr/VID_20230428_140439_2023101818313.avi';

    // convert mp4 to avi format
    FFmpegKit.executeAsync(
      '-i $selectedFilePath -c:v libx264 -c:a aac $outputPath',
      (Session session) async {
        final returnCode = await session.getReturnCode();

        if (ReturnCode.isSuccess(returnCode) == true) {
          Gal.putVideo(outputPath);
        }
      },
    );
```

</details>

### Environment

<details><summary>Logs</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on Manjaro Linux 5.15.125-1-MANJARO, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] Connected device (3 available)
[☠] Network resources (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: Network resources exceeded maximum allowed duration of 0:04:30.000000

! Doctor found issues in 1 category.
```

</details>

### Logs

<details><summary>Logs</summary>

```console
E/flutter ( 5527): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [GalException/NOT_SUPPORTED_FORMAT]: Unsupported file formats.
E/flutter ( 5527): #0      GalPlatform._invokeMethod (package:gal/src/gal_platform.dart:17:7)
E/flutter ( 5527): <asynchronous suspension>
E/flutter ( 5527): #1      GalPlatform.putVideo (package:gal/src/gal_platform.dart:24:5)
E/flutter ( 5527): <asynchronous suspension>
E/flutter ( 5527): #2      ConvertingCubit.saveOnGallery (package:fmkr/controller/converting/converting_cubit.dart:158:5)
```

</details>

**Comment by natsuk4ze** [comment]
Thank you for your contribution @husen-hn 🤝

### [The cause is that Android does not support `avi` as standard.](https://developer.android.com/guide/topics/media/media-formats)

you will need to change the out put file format to one that is supported. Like `mp4`.

```dart
String outputPath = ' /storage/emulated/0/Movies/fmkr/video.mp4';
```

This is a screenshot of the result of saving the same file to a file with the same code.
When I save the file as `avi`, the thumbnails do not show up and when I open the file, it jags and does not play properly. 


<img src="https://github.com/natsuk4ze/gal/assets/50433979/31f4d28d-3bea-4e42-b598-058b80594e1b" height="1000px">
