### ISSUE TITLE
Open Gallery to album

### ISSUE THREAD

**Issue by HoveringGoat** [natsuk4ze/gal#172]
### Proposal

Being able to save images to different albums is super nice but there isnt a great way in flutter (after much searching) to open a specific folder/album in gallery. Gals open is _okay_ but i know WHAT im trying to open to and would be much nicer for the user if they could jump straight there instead of having to do another navigate.

### Use case

being able to open a album/folder directly in the native app. For my use case is organizing the photos. Displaying them the default apps can do a better job. No need to reinvent the wheel here.

**Comment by natsuk4ze** [comment]
This issue will be closed, but will be reopened if a realization is found.

You can also mentions the owner at any time if you have questions.
