### ISSUE TITLE
Saving to album

### ISSUE THREAD

**Issue by natsuk4ze** [natsuk4ze/gal#18]
## Please leave 👍 if you need this feature

**Comment by natsuk4ze** [comment]
I'm beginning to understand, android completed without difficulty, but iOS may require breaking changes due to permissions.

**Comment by carrasc0** [comment]
This feature will be great

**Comment by natsuk4ze** [comment]
@carrasc0 But since there is only one 👍, it seems there are not many applicants 😅.

**Comment by natsuk4ze** [comment]
Now, I have finished working on v1.7.0 and I am ready to proceed this feature. However, I should understand if the package users would prefer to save it in the app-album like `gallery/my-app/image.jpg`, or if they want to use a custom name and save it to multiple album etc.

**Please leave stamp with this comment**
- app-album ->  🚀
- custom-name -> 🎉
