### ISSUE TITLE
Many of my android users report me this error - An unexpected error has occurred

### ISSUE THREAD

**Issue by alexislg2** [natsuk4ze/gal#188]
### Descrpition

I use gal 2.2.0 with flutter 3.16.4
I use gal to save photos downloaded from the internet. I have tried my app on several different phones and it works nicely. Unfortunately, at least 3 of my users experience this error "An unexpected error has occurred"

Here is my code:

```
await Gal.requestAccess(toAlbum: true);
final uri = Uri.parse(image_url);
final extension = path.extension(uri.path);
final filePath = '${Directory.systemTemp.path}/file.$extension';
await Dio().download(sending.image, filePath);
try {
  await Gal.putImage(filePath, album: "Familink");
  Fluttertoast.cancel();
  if (!context.mounted) return;
  Fluttertoast.showToast(
      msg: S.of(context).saved,
      toastLength: Toast.LENGTH_LONG,
      gravity: ToastGravity.CENTER,
      timeInSecForIosWeb: 1,
      fontSize: 16.0);
  break;
} on GalException catch (e) {
  Fluttertoast.cancel();
  if (!context.mounted) return;
  Fluttertoast.showToast(
      msg: e.type.message,
      toastLength: Toast.LENGTH_LONG,
      gravity: ToastGravity.CENTER,
      timeInSecForIosWeb: 1,
      fontSize: 16.0);
  break;
```

I have no idea how to debug this

**Comment by natsuk4ze** [comment]
Hi @alexislg2 👋

### 👩‍🏫 More detailed debugging information is needed.

Please collect as much of the following data as possible when that error occurs.

- `image_url`
- `filePath`
- `GalException.platformException`
- `GalException.stackTrace`
- Device info with [device_info_plus](https://pub.dev/packages/device_info_plus)

**Comment by alexislg2** [comment]
OK, I don't know yet how to collect that because as I said, I don't have the errors. Only a couple of users reported this to me and sent me the screenshot. I might try with crashalytics

**Comment by alexislg2** [comment]
I finally managed to get some stacktrace from crashlytics:

* Android 13
* Devie: CPH2247
* image_url = https://media.familinkframe.com/resized/2023/12/15/8ec58fe551764bacb2073979e1ee8558.jpg
* filePath = '${Directory.systemTemp.path}/file.jpg'

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: [GalException/UNEXPECTED]: An unexpected error has occurred.. Error thrown gal.
       at MethodChannelGal._invokeMethod(gal_method_channel.dart:16)
       at MethodChannelGal.putImage(gal_method_channel.dart:33)
       at SendingCard.build.<fn>(sending_card.dart:120)
```

**Comment by natsuk4ze** [comment]
OK. but there doesn't seem to be any logs that might help identify the cause of the error.

Did you get the `GalException.platformException` We need all the values of the PlatformException. It is very important because that is where the native code errors are stored.

**Comment by natsuk4ze** [comment]
By the way, does the 'sending.image' have the correct url value in it?

**Comment by alexislg2** [comment]
OK I will release a new version of my app, with more detailed logs in the crashlytics and wait for new logs to come...

This is 100% reproductible. The users who have this error have it 100% of the times, with 100% of the photos they try with.

**Comment by natsuk4ze** [comment]
### I am trying on Android 13 and cannot reproduce the error.

```dart
final path = '${Directory.systemTemp.path}/file.jpg';
await Dio().download(
  'https://media.familinkframe.com/resized/2023/12/15/8ec58fe551764bacb2073979e1ee8558.jpg',
  path,
);
await Gal.putImage(path, album: 'Familink');
```

<img src="https://github.com/natsuk4ze/gal/assets/50433979/2036db71-e8e6-4cd1-9f2f-5d1dbdea417a" width="300">

### Is the correct image downloaded in `filePath` before `Gal.putImage`?

**Comment by alexislg2** [comment]
Solved: the problem was caused by the destination file name: `file.jpg`

Some rare android devices were not able to overwrite it if a file with a similar name already exists in the album.

new code for downloading:
```
final uri = Uri.parse(image_url);
final filePath = '${Directory.systemTemp.path}/${uri.pathSegments.last';
await Dio().download(sending.image, filePath);
```

**Comment by alexislg2** [comment]
And by the way, with my original code, the file was named `file..jpg` instead of `file.jpg` because `path.extension(uri.path)` is equal to `.jpg`, not just `jpg`.

**Comment by natsuk4ze** [comment]
I'm glad you were able to resolve the issue 😊
> if a file with a similar name already exists in the album.

Is this  not **album** but **directory** ? This has nothing to do with the gallery, right?

**Comment by alexislg2** [comment]
Downloading a file to the temporary folder if a file already exists was not the issue. The error was raised when trying to save it to the album (only with some devices again):

`[GalException/UNEXPECTED]: An unexpected error has occurred.. Error thrown Failed to save image: java.lang.IllegalStateException: Failed to build unique file: /storage/emulated/0/Pictures/Familink/file..jpg`

**Comment by alexislg2** [comment]
You might consider to update your README. I can make a PR if you like

**Comment by alexislg2** [comment]
I cannot say and I cannot make any test (that would require to push a buggy version of the app in production). According to the error message, I would say it comes from the duplicate

Nevertheless, it's not a good thing to use the same file name as prevent from having multiple photos in the albul

**Comment by natsuk4ze** [comment]
The MediaStore API and custom java code should avoid duplicates, so duplicate filenames should not be the cause of the error.

Perhaps the file system did not recognize the file extension correctly because of the two dots in the file extension.

**Comment by natsuk4ze** [comment]
**Note**

I now know what the "Failed to build unique file" error message means.

If you try to save a file with a duplicate name, the system avoids this automatically. This is of the form "file(1).jpg". At this time, the system will probably separate the name from the extension by the position of the dot in the extension to generate a unique name. That's why it became such a gerrer when there were two extension dots, as in this case.

**Comment by Ilia-Nenashev-devX** [comment]
Seems I have similar issue. May be my file name "krutoscope_2025-10-14_222203.jpg" is not unique somtimes.

args size = 2
0 = {map entry} "path" -> "/data/user/0/ru.multistudia.krutoscope_dev/cache/krutoscope_2025-10-14_222203.jpg"
1 = {map entry} "album" -> "Krutoscope/Krutoscope Debug"

error = {PlatformException} PlatformException(UNEXPECTED, java.lang.NullPointerException: uri, 

com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:133)
android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1477)
android.content.ContentResolver.openOutputStream(ContentResolver.java:1227)
android.content.ContentResolver.openOutputStream(ContentResolver.java:1203)
studio.midoridesign.gal.GalPlugin.writeData(GalPlugin.java:144)
studio.midoridesign.gal.GalPlugin.putMedia(GalPlugin.java:125)
studio.midoridesign.gal.GalPlugin.lambda$onMethodCall$1$studio-midoridesign-gal-GalPlugin(GalPlugin.java:68)
studio.midoridesign.gal.GalPlugin$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
java.lang.Thread.run(Thread.java:919)


#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:367:18)
<asynchronous suspension>
#2      MethodChannelGal._invokeMethod (package:gal/src/gal_method_channel.dart:14:14)
<asynchronous suspension>
#3      MethodChannelGal.putImage (package:gal/src/gal_method_channel.dart:33:5)
<asynchronous suspension>
#4      AppStateProvider.copyImageFileToGallery (package:animascope/common/app_state_provider.dart:392:5)
<asynchronous suspension>
#5      AppStateProvider.updateProgress (package:animascope/common/app_state_provider.dart:487:7)
<asynchronous suspension>
#6      MainIsolate.applyLayout.<anonymous closure> (package:animascope/engine/main_isolate.dart:248:11)
<asynchronous suspension>
