### ISSUE TITLE
[REQUEST] Add ability to save media files from bytes (Uint8List)

### ISSUE THREAD

**Issue by kamranbekirovyz** [natsuk4ze/gal#20]
**Problem this request is trying to solve**
Hi. Today I started looking at packages for saving media files to the device gallery app and found this package very clean, maintained, and useful for this purpose. 

However, in order to save a media file that is on Memory (as bytes), I should do this: write to a temporary directory, then export to the gallery app.

<img width="526" alt="Screenshot 2023-07-03 at 19 11 47" src="https://github.com/natsuk4ze/gal/assets/59581562/325f28de-c980-4ac5-83fe-099b73f2cc6e">

Would you consider if I open a PR for this built-in feature which will require `path_provider` package as a dependency?

**Comment by natsuk4ze** [comment]
@kamranbekirovyz Thank you for your contribution🤟. Please wait as I investigate.

**Comment by natsuk4ze** [comment]
@kamranbekirovyz Can you provide more details?
What kind of use cases do you envision, like storing images taken with a camera?

**Comment by kamranbekirovyz** [comment]
There are low details on the issue because I was in a hurry 🙂

For example, [screenshot](https://pub.dev/packages/screenshot) package when takes a screenshot, the resulting image is not a `File`with path but byte data (`Uint8List`), so, you can not export it with `gal`: you need to save it with locally before. Is it more clear?

**Comment by natsuk4ze** [comment]
@kamranbekirovyz Thank you very much. I understand. If there is a lot of demand for it, maybe it should be included in the gal. However, if it can be solved with a few lines of code, it might be best to not include that functionality to keep the package minimalistic and provide documentation instead.

By the way, as you can see in the example, getting temporary folders can be accomplished with `Directory.systemTemp` without using `path_provider`.

**Comment by kamranbekirovyz** [comment]
Let me know if you need help in implementing this feature in future.

BTW, I'm working on an article that will promote `gal` as a preferred option for saving media files to the gallery app. I'll send you the article link when ready.

**Comment by natsuk4ze** [comment]
@kamranbekirovyz  Wow! That is great news. I appreciate it.

This is not finalized yet, but I may release a major update as a pre-release version.
The changes are as follows
- remove `hasAccess` and `requestAccess`
- add `toAlbum` option for saving media to app album

This will be released as a pre-release version, especially since the removal of the permission handle function is controversial.

**Comment by kamranbekirovyz** [comment]
Good Luck & keep in touch.

**Comment by natsuk4ze** [comment]
@kamranbekirovyz After a bit of thought, I decided to work on implementing the ability to save media in a `Uint8List`. Instead of using a temporary folder, I will pass `Uint8List` directly to the native code to save it.
It is probably possible.

**Comment by natsuk4ze** [comment]
Released🔥 Thank you for your request @kamranbekirovyz .
