### ISSUE TITLE
2.3.0 not compatible with gal_linux

### ISSUE THREAD

**Issue by lijianqiang12** [natsuk4ze/gal#209]
### Did you check the documentation and it did not help?

- [X] I have read the [README](https://github.com/natsuk4ze/gal/blob/main/README.md)
- [X] I have searched the [existing documentation](https://github.com/natsuk4ze/gal/wiki)
- [X] I have searched the [existing answer](https://github.com/natsuk4ze/gal/discussions)
- [X] I have read the [contribution guide](https://github.com/natsuk4ze/gal/blob/main/CONTRIBUTING.md)

### Overview

pub-cache/hosted/pub.dev/gal_linux-0.0.1/lib/src/gal_linux.dart:25:16: Error: The method 'GalPluginLinux.putImageBytes' has fewer named arguments than those of overridden method 'GalPlatform.putImageBytes'.
  Future<void> putImageBytes(Uint8List bytes, {String? album}) =>

pub-cache/hosted/pub.dev/gal-2.3.0/lib/src/gal_platform_interface.dart:23:16: Context: This is the overridden method ('putImageBytes').
  Future<void> putImageBytes(Uint8List bytes,

### Steps to reproduce

when i upgrade to gal 2.3.0

### Code sample

<details><summary>Code sample</summary>

```dart
flutter_quill
```

</details>

### Environment

<details><summary>Logs</summary>

```console
nothing
```

</details>

### Logs

<details><summary>Logs</summary>

```console
nothing
```

</details>

**Comment by natsuk4ze** [comment]
## This is a gal_linux issue, so please submit an issue to [that repository](https://github.com/ellet0/gal-linux). 

updating to gal 2.3.0 was not a destructive change for users. However, it was a destructive change for gal_linux as a non-endorsed federated plugin.
