### ISSUE TITLE
File name and return the new path

### ISSUE THREAD

**Issue by dryasbk** [natsuk4ze/gal#232]
### Did you check the documentation and it did not help?

- [X] I have carefully read the [README](https://github.com/natsuk4ze/gal/blob/main/README.md)
- [X] I have carefully searched the [existing documentation](https://github.com/natsuk4ze/gal/wiki)
- [X] I have carefully searched the [existing answer](https://github.com/natsuk4ze/gal/discussions)
- [X] I have carefully read the [contribution guide](https://github.com/natsuk4ze/gal/blob/main/CONTRIBUTING.md)

### Proposal

1- It would be very nice to add option to add new name for the image/ video. 
2-  Return the new path of the saved media in it is album.

### Use case

I am trying to save video from camera or pick it from gallery and save them in a special album for my app and save link in local database for easy back up of data, so just to copy exported database and the folder of media.

**Comment by natsuk4ze** [comment]
>1- It would be very nice to add option to add new name for the image/ video.

The `putImage` and `putImageBytes` already allow names to be specified.

**Comment by hoangcongtuan** [comment]
> > 1- It would be very nice to add option to add new name for the image/ video.
> 
> The `putImage` and `putImageBytes` already allow names to be specified. @dryasbk

The document and code did't have a file name parameter

**Comment by natsuk4ze** [comment]
You can create the file name as you like and simply pass the path to "putImage". We do not plan to add the ability to rename existing files to this plugin.

**Comment by Riz1ahmed** [comment]
Returning the Saved path I think is mandatory. for example, After saving, I want to preview the saved video. So without knowing the path, it is not possible.

**Comment by natsuk4ze** [comment]
> Returning the Saved path I think is mandatory

No. The file should exist locally at the time saveVideo is used. If so, simply specify the path to the file.

**Comment by natsuk4ze** [comment]
And here is why I am reluctant to work on this issue

- There are other ways to achieve the use case
- In order to get a pass on iOS, I would need full access to all photos, not just write permissions
- On iOS, getting the path to a file and manipulating it directly is deprecated
- The path can be changed by the user or the system without the app's intention -> it cannot be used as a temporary file path, so if that is the case, the path of a file already stored locally is sufficient

**Comment by natsuk4ze** [comment]
This request comes in frequently, but I have never seen the correct use case. Once we do, we put it in the Close and then in the FAQ, and reopen this again if necessary.

**Comment by natsuk4ze** [comment]
https://github.com/natsuk4ze/gal/discussions/224
