### ISSUE TITLE
Video saving into Picture folder

### ISSUE THREAD

**Issue by Riz1ahmed** [natsuk4ze/gal#236]
### Did you check the documentation and it did not help?

- [X] I have read the [README](https://github.com/natsuk4ze/gal/blob/main/README.md)
- [X] I have searched the [existing documentation](https://github.com/natsuk4ze/gal/wiki)
- [X] I have searched the [existing answer](https://github.com/natsuk4ze/gal/discussions)
- [X] I have read the [contribution guide](https://github.com/natsuk4ze/gal/blob/main/CONTRIBUTING.md)

When I am saving video with an album name (e.g. `await Gal.putVideo(tmpVideoPath.path, album: 'Intro Maker');`) the video saving into 'Picture/Intro Maker' directory.

My phone is a Galaxy s8, android v10 (Custom ROM).

**Comment by natsuk4ze** [comment]
We cannot respond until the DESCRIPTION item is filled

**Comment by natsuk4ze** [comment]
This behavior is currently as intended.

**Comment by Riz1ahmed** [comment]
What I will give in the description?

Now I have checked your code. In native you called same for both video and image

GalPlugin.java (line63)

` switch (call.method) {
            case "putVideo":
            case "putImage": {
                new Thread(() -> {
                    try {
`

And in the createContentValues method The condition Is (I think not right).

GalPlugin.java (line167)
```
private ContentValues createContentValues(boolean isImage, String name, String extension,
            String album) {
        ContentValues values = new ContentValues();
        String dirPath = isImage || album != null ? Environment.DIRECTORY_PICTURES
                : Environment.DIRECTORY_MOVIES;
 ......
```

**Comment by natsuk4ze** [comment]
> What I will give in the description?
Simply fill in the items as per the template. You have erased it and it is no longer visible.

**Comment by Riz1ahmed** [comment]
Now I have commented. Please check

**Comment by natsuk4ze** [comment]
When specifying a custom album, it is intended that it be created under Picture. I don't remember, but I think there was a reason it couldn't be created under Video🤔

**Comment by Riz1ahmed** [comment]
After I removing the `album != null` from the createContentValues method my video has been saved into 'Movies/Intro Maker' directory. So I think it is possible

And it not good practice to use your code by changing in my side. Because there could be more conditions which I don't know.

So please handle it

**Comment by natsuk4ze** [comment]
One thing I just remembered. I believe that this will result in a behavior that is not as intended for many people.

 For example, when you save a file with the folder name MyFolder, if you save it in Pictures for images and Movies for videos, two folders named MyFolder will be created.

**Comment by thanglq1** [comment]
Any update? Same issue with android 13, Samsung Galaxy A71. ```await Gal.putVideo(filePath, album: 'MyAlbum');```.  ```MyAlbum``` saved in Pictures instead of Movies and the video does not show in the Gallery.

**Comment by natsuk4ze** [comment]
As you can see from the thread above, this behavior is intentional and will not be changed. And this issue will be closed soon as there has been no reply from the author.

**Comment by Riz1ahmed** [comment]
Solved by:
I imported the library as a local into my project. And removed the '|| album != null' (from GalPlugin.java:172).

**Comment by natsuk4ze** [comment]
Yes. This change is not intentional for many people and should be made privately.

**Comment by Riz1ahmed** [comment]
I don't understand why many people would want the video to be saved in the Pictures directory.

**Comment by natsuk4ze** [comment]
Read the thread to find out. Let's say you are developing a camera app and you want to have a directory for your app. If you create separate directories depending on whether it was a photo or a video that was taken, users will be confused.

**Comment by natsuk4ze** [comment]
Read the thread to find out. Let's say you are developing a camera app and you want to have a directory for your app. If you create separate directories depending on whether it was a photo or a video that was taken, users will be confused.

**Comment by Riz1ahmed** [comment]
For those types of cases (e.g. camera app) there should be a boolean variable _isSingleDir_. If **false**, it should be a separate folder (as I'm thinking). If **true**, there could be two solutions:
1. The folder will be created into the **Camera (DCIM)** folder. All the videos & images will be saved (for the Camera app) here
2. The folder will be created into the storage root folder (not inside the Pictures folder) with the given name.

**Comment by natsuk4ze** [comment]
I cannot support that approach because it is not aesthetic. 
And we need to know the use case in more detail: do you want to create your own album in the Movie folder? And your app only stores videos?

**Comment by Riz1ahmed** [comment]
Yes. My app now creates only videos (an image feature could be added in the future). I need to save the video inside the user's video directory (Videos/Movies).

**Comment by natsuk4ze** [comment]
Thank you very much. I am looking for a clean approach on this issue, but currently no quality ideas exist that can be merged into the main branch.

My goal is to make this plugin simple and easy to use for many people, and most importantly, it needs to be supported in the long term. For this reason, I may be cautious about adding features. Thank you for your understanding.
